@echo off
cd /d "%~dp0"
echo Test 1: Starting...
echo Test 2: Node check...
where node >nul 2>nul && echo OK: Node found || echo FAIL: Node not found
echo Test 3: Version...
node --version
npm --version
echo Test 4: After version check...
timeout /t 3 /nobreak >nul
echo Test 5: Continuing...
echo Test 6: Done!
pause
